"""
Tool: Business Setup — Context File Writer
Purpose: Takes structured JSON answers from the setup wizard and writes
         consistent context files (my-business.md, my-voice.md).
Usage: python3 scripts/init_business.py --answers '{"business": {...}, "voice": {...}}'
       OR called programmatically by the setup wizard skill.
"""

import argparse
import json
import sys
from datetime import datetime
from pathlib import Path

PROJECT_ROOT = Path(__file__).parent.parent.parent.parent.parent


def write_business_context(answers: dict, output_path: Path) -> str:
    """Write context/my-business.md from Phase 1 answers."""
    biz = answers.get("business", {})

    content = f"""# My Business

## Overview
{biz.get('description', '(not provided)')}

## Target Customer
{biz.get('customers', '(not provided)')}

## Main Offer
{biz.get('offer', '(not provided)')}

## Lead Sources
{biz.get('lead_sources', '(not provided)')}

## Current Challenge
{biz.get('challenge', '(not provided)')}

---
*Generated by Iris setup wizard on {datetime.now().strftime('%Y-%m-%d')}*
"""
    output_path.write_text(content)
    return str(output_path)


def write_voice_context(answers: dict, output_path: Path) -> str:
    """Write context/my-voice.md from Phase 2 answers."""
    voice = answers.get("voice", {})

    content = f"""# My Voice

## Communication Style
{voice.get('style', '(not provided)')}

## Sample (How I Actually Sound)
{voice.get('sample', '(not provided)')}

## Words & Phrases I Use
{voice.get('phrases', '(not provided)')}

## What I NEVER Sound Like
{voice.get('anti_patterns', '(not provided)')}

---

## Quick Reference for AI

When writing as me:
- Match the style described above
- Use my characteristic phrases naturally
- Avoid the anti-patterns listed
- When in doubt, re-read the sample text — that's the target

---
*Generated by Iris setup wizard on {datetime.now().strftime('%Y-%m-%d')}*
"""
    output_path.write_text(content)
    return str(output_path)


def main():
    parser = argparse.ArgumentParser(description="Write business context files from wizard answers")
    parser.add_argument("--answers", type=str, required=True, help="JSON string of wizard answers")
    parser.add_argument("--project-root", type=str, default=str(PROJECT_ROOT), help="Project root path")
    args = parser.parse_args()

    try:
        answers = json.loads(args.answers)
    except json.JSONDecodeError as e:
        print(f"Error parsing JSON: {e}", file=sys.stderr)
        sys.exit(1)

    root = Path(args.project_root)

    results = {}

    if "business" in answers:
        path = write_business_context(answers, root / "context" / "my-business.md")
        results["business_context"] = path

    if "voice" in answers:
        path = write_voice_context(answers, root / "context" / "my-voice.md")
        results["voice_context"] = path

    print(json.dumps(results, indent=2))


if __name__ == "__main__":
    main()
