"""
IRIS Core -- First-time setup.
Run this once to configure your API keys. Creates the .env file automatically.
"""

import getpass
import os
import re
import sys
from pathlib import Path


ENV_PATH = Path(__file__).parent / ".env"
EXAMPLE_PATH = Path(__file__).parent / ".env.example"

KEYS = [
    {
        "key": "TELEGRAM_BOT_TOKEN",
        "label": "Telegram bot token (from @BotFather)",
        "pattern": r"^\d+:[A-Za-z0-9_-]{35,}$",
        "error": "Should look like 123456789:ABCdefGHI... -- copy the full token from BotFather.",
        "secret": True,
    },
    {
        "key": "ANTHROPIC_API_KEY",
        "label": "Anthropic API key (from console.anthropic.com)",
        "pattern": r"^sk-ant-",
        "error": "Should start with sk-ant- -- copy the full key from your Anthropic dashboard.",
        "secret": True,
    },
    {
        "key": "BOT_USERNAME",
        "label": "Bot username, without the @ (e.g. IrisAccountabilityBot)",
        "pattern": r"^[A-Za-z0-9_]{5,}$",
        "error": "Just the username, no @ symbol. Letters, numbers, underscores only.",
        "secret": False,
        "default": "IrisAccountabilityBot",
    },
]

# Keys that get default values without prompting
DEFAULTS = {
    "ANTHROPIC_MODEL": "claude-sonnet-4-20250514",
    "WEB_PORT": "8080",
    "PRO_URL": "https://iris-ai.co",
}


def prompt_for_key(key_info: dict) -> str:
    """Prompt the user for a single key, validating format."""
    label = key_info["label"]
    default = key_info.get("default")

    if default:
        label += f" [{default}]"

    while True:
        if key_info.get("secret"):
            value = getpass.getpass(f"  {label}: ").strip()
        else:
            value = input(f"  {label}: ").strip()

        # Accept default on empty input
        if not value and default:
            return default

        if not value:
            print("    Can't be empty. Try again.")
            continue

        # Validate format
        pattern = key_info.get("pattern")
        if pattern and not re.match(pattern, value):
            print(f"    {key_info['error']}")
            continue

        return value


def setup():
    """Run the interactive setup."""
    print()
    print("  IRIS Core -- Setup")
    print("  " + "-" * 20)
    print()

    if ENV_PATH.exists():
        confirm = input("  .env file already exists. Overwrite? (y/n): ").strip().lower()
        if confirm != "y":
            print("  Setup cancelled.")
            return

    print("  I need two API keys and your bot username.")
    print("  Keys are hidden as you type -- that's normal.")
    print()

    collected = {}
    for key_info in KEYS:
        collected[key_info["key"]] = prompt_for_key(key_info)

    # Build the .env content
    lines = [
        "# IRIS Core -- Environment Variables",
        f"# Generated by setup.py",
        "",
        f"ANTHROPIC_API_KEY={collected['ANTHROPIC_API_KEY']}",
        f"ANTHROPIC_MODEL={DEFAULTS['ANTHROPIC_MODEL']}",
        "",
        f"TELEGRAM_BOT_TOKEN={collected['TELEGRAM_BOT_TOKEN']}",
        f"BOT_USERNAME={collected['BOT_USERNAME']}",
        "",
        f"WEB_PORT={DEFAULTS['WEB_PORT']}",
        f"PRO_URL={DEFAULTS['PRO_URL']}",
        "",
    ]

    ENV_PATH.write_text("\n".join(lines))
    os.chmod(ENV_PATH, 0o600)

    print()
    print("  Saved. Keys are in .env (permissions locked to your user).")
    print()
    print("  To run the bot:")
    print("    python3 bot.py")
    print()


if __name__ == "__main__":
    setup()
