#!/bin/bash
# ============================================================
# Build a clean IRIS release zip for distribution
# Excludes: credentials, databases, personal data, dev files
# Output: ../Iris-Pro-Release.zip (ready for Lemon Squeezy)
# ============================================================

set -e

IRIS_DIR="$(cd "$(dirname "$0")/.." && pwd)"
cd "$IRIS_DIR"

FOLDER_NAME="$(basename "$IRIS_DIR")"
OUTPUT="${IRIS_DIR}/../IRIS-Release.zip"

echo ""
echo "  Building IRIS release package..."
echo ""

# Remove old release if exists
rm -f "$OUTPUT"

# Reset context files to placeholders (so your personal data doesn't ship)
echo "  Resetting context files to placeholders..."

PLACEHOLDER_BIZ="# My Business

> Populated during IRIS onboarding (iris-setup skill).
> Do not edit this file directly."

PLACEHOLDER_VOICE="# My Voice

> Populated during IRIS onboarding (iris-setup skill).
> Do not edit this file directly."

PLACEHOLDER_EVEREST="# My Mt. Everest

> Long-term vision, 3-5 year goals, core priorities, and non-negotiables.
> Populated by the Controlled Calendar skill.

---"

# Back up your current files
mkdir -p .tmp/context-backup
cp context/my-business.md .tmp/context-backup/ 2>/dev/null || true
cp context/my-voice.md .tmp/context-backup/ 2>/dev/null || true
cp context/my-mteverest.md .tmp/context-backup/ 2>/dev/null || true

# Write placeholders
echo "$PLACEHOLDER_BIZ" > context/my-business.md
echo "$PLACEHOLDER_VOICE" > context/my-voice.md
echo "$PLACEHOLDER_EVEREST" > context/my-mteverest.md

# Reset memory to clean factory state
cp memory/MEMORY.md .tmp/context-backup/ 2>/dev/null || true
cp memory/core-state.json .tmp/context-backup/ 2>/dev/null || true
cp memory/audit-log.jsonl .tmp/context-backup/ 2>/dev/null || true

cat > memory/MEMORY.md << 'MEMEOF'
# Persistent Memory

> Not yet configured. Run iris-setup to populate.
MEMEOF

cat > memory/core-state.json << 'CSEOF'
{
  "_meta": {
    "version": 1,
    "last_updated_at": null,
    "last_confirmed_at": null,
    "source_of_last_write": "system_canonical",
    "audit_log_ref": "memory/audit-log.jsonl",
    "_field_timestamps": {}
  },
  "identity": { "name": "", "role": "", "business_name": "", "business_type": "" },
  "current_goals": { "primary": "", "secondary": [], "horizon": "short", "last_stated_at": null },
  "offer_stack": { "products": [], "pricing_last_confirmed_at": null },
  "tone_preferences": { "communication_style": "", "writing_voice": "", "avoid": [] },
  "active_commitments": [],
  "active_project_context": [],
  "canonical_business_facts": { "target_audience": "", "primary_platform": "", "location": "", "custom": {} }
}
CSEOF

# Clear append-only logs, wiki, and ALL session logs (both memory paths)
> memory/audit-log.jsonl
> memory/pending-writes.jsonl 2>/dev/null || true
> memory/ingest-log.jsonl 2>/dev/null || true
rm -f memory/wiki/*.md 2>/dev/null || true
rm -f memory/logs/*.md memory/logs/*.log 2>/dev/null || true
rm -f .claude/memory/logs/*.md .claude/memory/logs/*.log 2>/dev/null || true

# Build zip, excluding personal/dev files
cd "$IRIS_DIR/.."
zip -r "$OUTPUT" "$FOLDER_NAME/" \
    -x "${FOLDER_NAME}/.env" \
    -x "${FOLDER_NAME}/data/*.db" \
    -x "${FOLDER_NAME}/data/*.db-*" \
    -x "${FOLDER_NAME}/data/capture_markers/*" \
    -x "${FOLDER_NAME}/data/auto_capture.log" \
    -x "${FOLDER_NAME}/memory/logs/*" \
    -x "${FOLDER_NAME}/.claude/memory/logs/*" \
    -x "${FOLDER_NAME}/logs/*" \
    -x "${FOLDER_NAME}/.tmp/*" \
    -x "${FOLDER_NAME}/.git/*" \
    -x "${FOLDER_NAME}/.claude/settings.local.json" \
    -x "${FOLDER_NAME}/.claude/launch.json" \
    -x "${FOLDER_NAME}/.claude/plans/*" \
    -x "${FOLDER_NAME}/.claude/scheduled-tasks/*" \
    -x "${FOLDER_NAME}/scripts/build-release.sh" \
    -x "${FOLDER_NAME}/node_modules/*" \
    -x "${FOLDER_NAME}/venv/*" \
    -x "${FOLDER_NAME}/__pycache__/*" \
    -x "*/__pycache__/*" \
    -x "*.pyc" \
    -x ".DS_Store" \
    -x "*/.DS_Store" \
    > /dev/null

cd "$IRIS_DIR"

# Verify
SIZE=$(du -h "$OUTPUT" | awk '{print $1}')
FILES=$(zipinfo -1 "$OUTPUT" 2>/dev/null | wc -l | tr -d ' ')

echo "  ✓ Built: $OUTPUT"
echo "  ✓ Size: $SIZE"
echo "  ✓ Files: $FILES"
echo ""

# Safety check — make sure no secrets leaked
echo "  Checking for leaked secrets..."
LEAKED=$(zipinfo -1 "$OUTPUT" 2>/dev/null | grep -E "^${FOLDER_NAME}/\.env$|\.db$" | head -5)
if [ -n "$LEAKED" ]; then
    echo "  ⚠ WARNING: These files should not be in the zip:"
    echo "$LEAKED" | while read f; do echo "    - $f"; done
    echo ""
else
    echo "  ✓ No credentials or databases in package"
fi

# Restore your personal context files
echo "  Restoring your context files..."
cp .tmp/context-backup/my-business.md context/ 2>/dev/null || true
cp .tmp/context-backup/my-voice.md context/ 2>/dev/null || true
cp .tmp/context-backup/my-mteverest.md context/ 2>/dev/null || true
cp .tmp/context-backup/MEMORY.md memory/ 2>/dev/null || true
cp .tmp/context-backup/core-state.json memory/ 2>/dev/null || true
cp .tmp/context-backup/audit-log.jsonl memory/ 2>/dev/null || true
rm -rf .tmp/context-backup

echo ""
echo "  Ready to upload to Lemon Squeezy."
echo ""
