"""
Tool: Business Setup — Context File Writer
Purpose: Takes structured JSON answers from the setup wizard and writes
         consistent context files (my-business.md, my-voice.md).
Usage: python3 scripts/init_business.py --answers '{"business": {...}, "voice": {...}}'
       OR called programmatically by the setup wizard skill.
"""

import argparse
import json
import sys
from datetime import datetime
from pathlib import Path

PROJECT_ROOT = Path(__file__).parent.parent.parent.parent.parent


def write_business_context(answers: dict, output_path: Path) -> str:
    """Write context/my-business.md from Phase 1 answers."""
    biz = answers.get("business", {})

    content = f"""# My Business

## Overview
{biz.get('description', '(not provided)')}

## Target Customer
{biz.get('customers', '(not provided)')}

## Main Offer
{biz.get('offer', '(not provided)')}

## Lead Sources
{biz.get('lead_sources', '(not provided)')}

## Current Challenge
{biz.get('challenge', '(not provided)')}

---
*Generated by Iris setup wizard on {datetime.now().strftime('%Y-%m-%d')}*
"""
    output_path.write_text(content)
    return str(output_path)


def write_voice_context(answers: dict, output_path: Path) -> str:
    """Write context/my-voice.md from Phase 2 answers."""
    voice = answers.get("voice", {})

    content = f"""# My Voice

## Communication Style
{voice.get('style', '(not provided)')}

## Observed Patterns
{voice.get('sample', voice.get('observed_patterns', '(not provided)'))}

## Words & Phrases I Use
{voice.get('phrases', '(not provided)')}

## What I NEVER Sound Like
{voice.get('anti_patterns', '(not provided)')}

---

## Quick Reference for AI

When writing as me:
- Match the style described above
- Use my characteristic phrases naturally
- Avoid the anti-patterns listed
- When in doubt, re-read the observed patterns — that's the target

---
*Generated by Iris setup wizard on {datetime.now().strftime('%Y-%m-%d')}*
"""
    output_path.write_text(content)
    return str(output_path)


def import_core_bridge(email: str, core_url: str = "https://iris-ai.co") -> dict | None:
    """Import Mt. Everest data from IRIS Core via the bridge API.

    Args:
        email: User's email (used during Core signup).
        core_url: Base URL of the IRIS Core instance.

    Returns dict with summary + completed_at, or None if not found.
    """
    import urllib.request
    import urllib.error

    url = f"{core_url}/api/bridge/{email.strip().lower()}"
    try:
        req = urllib.request.Request(url, method="GET")
        with urllib.request.urlopen(req, timeout=10) as resp:
            data = json.loads(resp.read().decode())
            if data.get("success") and data.get("summary"):
                return data
    except (urllib.error.URLError, urllib.error.HTTPError, json.JSONDecodeError, Exception) as e:
        print(f"Bridge import failed: {e}", file=sys.stderr)
    return None


def write_mt_everest_from_bridge(summary: str, output_path: Path) -> str:
    """Write context/my-mteverest.md from a Core bridge import."""
    # Parse the summary sections
    goal = ""
    why = ""
    ceiling = ""
    identity = ""
    milestones = ""

    in_milestones = False
    for line in summary.split("\n"):
        stripped = line.strip()
        upper = stripped.upper()

        if upper.startswith("THE GOAL:"):
            goal = stripped.split(":", 1)[1].strip()
            in_milestones = False
        elif upper.startswith("WHY THIS GOAL:"):
            why = stripped.split(":", 1)[1].strip()
            in_milestones = False
        elif upper.startswith("THE CEILING:"):
            ceiling = stripped.split(":", 1)[1].strip()
            in_milestones = False
        elif upper.startswith("WHO I NEED TO BECOME:"):
            identity = stripped.split(":", 1)[1].strip()
            in_milestones = False
        elif upper.startswith("MILESTONES"):
            in_milestones = True
            continue

        if in_milestones and stripped:
            milestones += stripped + "\n"

    content = f"""# My Mt. Everest

## The Goal
{goal}

## Why This Goal
{why}

## Who I Need to Become
{identity}

## The Ceiling
{ceiling}

## Milestones
{milestones.strip()}

---
*Imported from IRIS Core on {datetime.now().strftime('%Y-%m-%d')}*
"""
    output_path.write_text(content)
    return str(output_path)


def main():
    parser = argparse.ArgumentParser(description="Write business context files from wizard answers")
    parser.add_argument("--answers", type=str, required=True, help="JSON string of wizard answers")
    parser.add_argument("--project-root", type=str, default=str(PROJECT_ROOT), help="Project root path")
    parser.add_argument("--import-core", type=str, help="Email to import Mt. Everest from IRIS Core")
    parser.add_argument("--core-url", type=str, default="https://iris-ai.co", help="IRIS Core base URL")
    args = parser.parse_args()

    root = Path(args.project_root)
    results = {}

    # Bridge import from Core
    if args.import_core:
        bridge_data = import_core_bridge(args.import_core, args.core_url)
        if bridge_data:
            path = write_mt_everest_from_bridge(
                bridge_data["summary"],
                root / "context" / "my-mteverest.md",
            )
            results["mt_everest_imported"] = True
            results["mt_everest_path"] = path
            print(f"Imported Mt. Everest from Core for {args.import_core}")
        else:
            results["mt_everest_imported"] = False
            print(f"No Core session found for {args.import_core}")

    try:
        answers = json.loads(args.answers) if args.answers != "{}" else {}
    except json.JSONDecodeError as e:
        print(f"Error parsing JSON: {e}", file=sys.stderr)
        sys.exit(1)

    if "business" in answers:
        path = write_business_context(answers, root / "context" / "my-business.md")
        results["business_context"] = path

    if "voice" in answers:
        path = write_voice_context(answers, root / "context" / "my-voice.md")
        results["voice_context"] = path

    print(json.dumps(results, indent=2))


if __name__ == "__main__":
    main()
